- hosts: localhost
  vars:
    username: corey
  roles:
    - role: cmprescott.chrome
      become: true
  tasks:
    - copy:
        src: etc/sudoers.d/custom-policy
        dest: /etc/sudoers.d/custom-policy
        owner: root
        mode: 0664
      become: true
    # Create folders
    - file: 
        path: ~/webapps/ 
        state: directory
    - file:
        path: ~/ansibles/
        state: directory
    - file: 
        path: ~/debs/ 
        state: directory
      become: true
    - apt_key: 
        keyserver: hkp://pgp.mit.edu:80 
        id: 379CE192D401AB61
      become: true
    - apt_repository: 
        repo: deb [arch=amd64] https://dl.bintray.com/resin-io/debian stable etcher
      become: true
    - apt_key: 
        url: https://packages.microsoft.com/keys/microsoft.asc
      become: true
    - apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
      become: true
    - apt_repository:
        repo: ppa:papirus/papirus
      become: true
    - apt_key: 
        url: https://jgeboski.github.io/obs.key
      become: true
    - apt_repository: 
        repo: deb http://download.opensuse.org/repositories/home:/jgeboski/xUbuntu_17.10 ./
      become: true
    - apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present
      become: true
    - apt_repository:
        repo: deb https://dl.yarnpkg.com/debian/ stable main
        state: present
        filename: yarn.list
      become: true
    - apt: 
        name: "{{ item }}"
        state: installed 
        update_cache: yes
      with_items:
        - curl
        - build-essential
        - powertop
        - python-pip
        - python3-pip
        - python3-venv
        - git
        - pidgin
        - pidgin-otr
        - pidgin-plugin-pack
        - purple-facebook
        - tmux
        - tigervnc-viewer
        - gparted
        - cantata
        - quodlibet
        - exfalso
        - code
        - etcher-electron
        - furiusisomount
        - arc-theme
        - numix-gtk-theme
        - numix-icon-theme
        - papirus-icon-theme
        - vlc
        - nodejs
        - yarn
      become: true
    - name: download deadbeef
      get_url: 
        url: http://sourceforge.net/projects/deadbeef/files/debian/deadbeef-static_0.7.2-2_amd64.deb/download
        dest: downloads/deadbeef-static_0.7.2-2_amd64.deb
    - apt:
        deb: downloads/deadbeef-static_0.7.2-2_amd64.deb
      become: true
    - file:
        path: downloads/deadbeef/
        state: directory
    - get_url:
        url: http://sourceforge.net/projects/deadbeef/files/plugins/x86_64/ddb_musical_spectrum-215bbad-x86_64.zip/download
        dest: downloads/
    - unarchive:
        src: downloads/ddb_musical_spectrum-215bbad-x86_64.zip
        dest: downloads/deadbeef/
    - get_url:
        url: http://sourceforge.net/projects/deadbeef/files/plugins/x86_64/ddb_spectrogram-8d1b371-x86_64.zip/download
        dest: downloads/
    - unarchive:
        src: downloads/ddb_spectrogram-8d1b371-x86_64.zip
        dest: downloads/deadbeef/
    - get_url:
        url: http://sourceforge.net/projects/deadbeef/files/plugins/x86_64/infobar-85debeadd327-x86_64.zip/download
        dest: downloads/
    - unarchive:
        src: downloads/infobar-85debeadd327-x86_64.zip
        dest: downloads/deadbeef/
    - name: copy all downloaded deadbeef plugins
      copy:
        src: "{{item}}"
        dest: /opt/deadbeef/lib/deadbeef
      with_fileglob:
        - downloads/deadbeef/plugins/*
      become: true
    - name: download soulseekqt
      get_url:
        url: https://www.dropbox.com/s/wborsit53rlj7bz/SoulseekQt-$_pkgver-64bit.AppImage?dl=1
        dest: /opt/soulseekqt.appimage
        mode: a+rwx
      become: true
    - name: symlink /usr/bin/soulseekqt to appimage
      file:
        path: /usr/bin/soulseekqt
        src: /opt/soulseekqt.appimage
        mode: a+rwx
        state: link
      become: true
    - sysctl:
        name: fs.inotify.max_user_watches
        value: 524288
      become: true
    - sysctl:
        name: fs.file-max
        value: 500000
      become: true
    - get_url:
        url: https://github.com/source-foundry/Hack/releases/download/v3.000/Hack-v3.000-ttf.zip
        dest: /tmp/
    - file:
        path: /usr/share/fonts/truetype/Hack/
        state: directory
      become: true
    - unarchive:
        src: /tmp/Hack-v3.000-ttf.zip
        dest: /usr/share/fonts/truetype/Hack/
        creates: /usr/share/fonts/truetype/Hack/Hack-Regular.ttf
      become: true
    - shell: fc-cache && mkfontscale /usr/share/fonts/truetype/Hack/ && mkfontdir /usr/share/fonts/truetype/Hack/
      become: true
